#!/usr/bin/env bash

# Base color definitions (256-color codes and HEX)
COLOR_LIGHT_CYAN3="color159"
COLOR_DARK_MAGENTA="color91"
COLOR_YELLOW1="color226"
COLOR_GREEN4="color22"
COLOR_GREY93="color255"
COLOR_DARK_RED_NEW="#2E0000"
COLOR_WHITE="#FFFFFF"
COLOR_DARK_ORANGE3="color166"
COLOR_RED3="color160"
COLOR_DEEP_PINK4="color89"
COLOR_DARK_RED="color52"
COLOR_CHARTREUSE1="color118"
COLOR_CYAN="color14"
COLOR_DARK_BLUE="color18"

# Window status
COLOR_WINDOW_ACTIVE_TEXT="#[fg=${COLOR_YELLOW1},bg=${COLOR_GREEN4}]"
COLOR_WINDOW_ACTIVE_SEP="#[fg=${COLOR_GREEN4},bg=${COLOR_DARK_RED_NEW}]"

# Left status bar: tmux version
COLOR_TMUX_VERSION_TEXT="#[fg=${COLOR_LIGHT_CYAN3},bg=${COLOR_DARK_MAGENTA}]"
COLOR_TMUX_VERSION_SEP="#[fg=${COLOR_DARK_MAGENTA},bg=${COLOR_DARK_RED_NEW}]"

# Left status bar: hostname
COLOR_HOSTNAME_TEXT="#[fg=${COLOR_WHITE},bg=${COLOR_DARK_ORANGE3}]"
COLOR_HOSTNAME_SEP="#[fg=${COLOR_DARK_ORANGE3},bg=${COLOR_DARK_RED_NEW}]"

# Left status bar: session name
COLOR_SESSION_TEXT="#[fg=${COLOR_YELLOW1},bg=${COLOR_RED3}]"
COLOR_SESSION_SEP="#[fg=${COLOR_RED3},bg=${COLOR_DARK_RED_NEW}]"

# Right status bar: CPU
COLOR_CPU_TEXT="#[fg=${COLOR_YELLOW1},bg=${COLOR_DEEP_PINK4}]"
COLOR_CPU_SEP="#[fg=${COLOR_DEEP_PINK4},bg=${COLOR_DARK_RED_NEW}]"

# Right status bar: RAM
COLOR_RAM_TEXT="#[fg=${COLOR_YELLOW1},bg=${COLOR_DARK_RED}]"
COLOR_RAM_SEP="#[fg=${COLOR_DARK_RED},bg=${COLOR_DARK_RED_NEW}]"

# Icon separators (shared)
COLOR_ICON_SEP="#[fg=${COLOR_GREY93},bg=${COLOR_DARK_RED_NEW}]"

# Second line: side timezone (Melbourne / Vietnam)
COLOR_TIMEZONE_SIDE_LABEL="#[fg=${COLOR_CHARTREUSE1},bg=${COLOR_DARK_RED_NEW}]"
COLOR_TIMEZONE_SIDE_VALUE="#[fg=${COLOR_CYAN},bg=${COLOR_DARK_RED_NEW}]"

# Second line: center timezone (CET)
COLOR_TIMEZONE_CENTER_SEP="#[fg=${COLOR_DARK_BLUE},bg=${COLOR_DARK_RED_NEW}]"
COLOR_TIMEZONE_CENTER_LABEL="#[fg=${COLOR_CHARTREUSE1},bg=${COLOR_DARK_BLUE}]"
COLOR_TIMEZONE_CENTER_ICON="#[fg=${COLOR_GREY93},bg=${COLOR_DARK_BLUE}]"
COLOR_TIMEZONE_CENTER_VALUE="#[fg=${COLOR_YELLOW1},bg=${COLOR_DARK_BLUE}]"

# Background color of status bar
COLOR_BACKGROUND="fg=${COLOR_WHITE},bg=${COLOR_DARK_RED_NEW}"
